name: 프론트엔드 배포

on:
  push:
    branches: #target
      - dev
      - main
    paths:
      - "client/**"
  pull_request:
    branches: #target
      - dev
      - main
    paths:
      - "client/**"
  workflow_dispatch:

env:
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: client/yarn.lock
      - name: Generate env file for production
        run: |
          cd client
          echo "BE_URL=$BE_URL" >> .env.production
        env:
          BE_URL: ${{ secrets.BE_URL }}
      - name: Build client files
        working-directory: ./client
        run: |
          yarn install
          yarn build
      - name: Zip distributions
        run: zip -r picnic.zip ./client ./appspec.yml ./scripts
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./picnic.zip s3://picnic-map-bucket/public/

      - name: Deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name picnic-map-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name picnic-deploy-group
          --s3-location bucket=picnic-map-bucket,bundleType=zip,key=public/picnic.zip
